# Default values for exporter-weather.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/nullify005/chat-hvac
  pullPolicy: IfNotPresent
  tag: v0.1.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "false"
  prometheus.io/path: /metrics
  prometheus.io/port: "2113"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

resources:
  limits:
    memory: 32Mi
  requests:
    memory: 32Mi

livenessProbe:
  path: /health
  port: 2113
readinessProbe:
  path: /health
  port: 2113

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

command:
- /chat-hvac

secrets:
- config.yaml
