helmDefaults:
  wait: true
  atomic: true
  verify: false # necessary as this is a local chart
  timeout: 30

environments:
  local: {}
  development: {}

releases:
- name: app
  namespace: chat-hvac-v1
  createNamespace: true
  chart: ../helm/charts/chat-hvac
  missingFileHandler: Warn
  # values:
  # - ../helm/values/app/{{ .Environment.Name }}.yaml
